spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.4.9:3306/blogs?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: duyicheng
  session:
    store-type: redis
    timeout: 60  # 一个小时
  redis:
    host: 10.0.4.9
    port: 6379
    password: seventeen
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0


logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log

server:
  port: 80
